# Site settings
title: His name is Michael Paulson
email:
description: > # this means to ignore newlines until "baseurl:"
    Enterprise javascript, its like building desktop applications in an
    unstable, less reliable os.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michaelbpaulson.github.io" # the base hostname & protocol for your site
twitter_username: _michaelpaulson
github_username:  michaelbpaulson

# Build settings
markdown: kramdown
